#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG_INFORMATION                  101
#define IDR_MENU_TRAY                           103
#define IDD_DIALOG_SETTINGS                     105
#define IDD_DIALOG_PATHS                        111
#define IDD_DIALOG_FILES                        114
#define IDI_ICON_APP                            118
#define IDD_DIALOG_DROPDOWNLIST                 119
#define IDD_DIALOG_HOTKEY                       121
#define IDD_DIALOG_GENERAL                      123
#define IDC_BUTTON_ADDENVPATH                   1001
#define IDC_BUTTON_DELETEFILE                   1001
#define IDC_CHECKBOX_AUTOSTART                  1001
#define IDC_CHECKBOX_EXECONSOLEAPP              1002
#define IDC_EDIT_HOTKEY                         1002
#define IDC_CHECKBOX_CTRLPN                     1003
#define IDC_EDIT_INFORMATION                    1003
#define IDC_BUTTON_CLEARALL                     1005
#define IDC_BUTTON_UPDATEFILES                  1006
#define IDC_EDIT_SINGLEFILE                     1010
#define IDM_ABOUT                               40000
#define IDM_QUIT                                40001
#define IDM_SETTINGS                            40002
#define IDC_TREE_SETTINGS                       40004
#define IDC_BUTTON_DELPATH                      40014
#define IDC_BUTTON_ADDPATH                      40015
#define IDC_BUTTON_BROWSE                       40016
#define IDC_EDIT_PATH                           40017
#define IDC_LIST_FILES                          40018
#define IDC_LIST_PATH                           40018
#define IDC_EDIT_FILTERS                        40020
#define IDC_CHECKBOX_EXECALL                    40024
#define IDC_CHECKBOX_CTRL                       40025
#define IDC_CHECKBOX_ALT                        40027
#define IDC_CHECKBOX_SHIFT                      40029
#define IDC_CHECKBOX_WIN                        40031
#define IDC_BUTTON_CANCEL                       40033
#define IDC_BUTTON_APPLY                        40034
#define IDC_EDIT_DROPDONWITEM                   40037
#define IDC_EDIT_HOTKEY_DEC                     40037
#define IDC_CHECKBOX_ENABLEDROPDOWNLIST         40039
#define IDC_CHECKBOX_CTRLKJ                     40040
#define IDC_CHECKBOX_UPDOWN                     40041
#define IDC_BUTTON_BROWSEFILE                   40044
#define IDC_CHECKBOX_TAB                        40044
#define IDC_EDIT_SINGLEKEY                      40045
#define IDC_BUTTON_ADDSINGLEFILE                40046
#define IDC_BUTTON_ADDINTCMD                    40047
#define IDC_BUTTON_ADDSTARTMENU                 40048
